spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: spring-boot-group
      client-id: spring-boot-client
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      topic: topic3
